#!/usr/bin/env bash
# =============================================================================
# NarcoScope 24/7 data collector
# =============================================================================
# Runs the open-data pipeline (fetch -> transform -> VALIDATE), and pushes the
# refreshed datasets only if they changed AND passed the test gate. Designed to
# run on the Hetzner box under a systemd timer.
#
# Safety: `npm run data:refresh` runs tsc + the full vitest suite (including the
# dataset-integrity tests) as a hard gate. If validation fails, the script exits
# non-zero and pushes NOTHING. The pipeline runs in a disposable detached
# worktree, so failed generated files never dirty or overwrite the service repo.
# =============================================================================
set -euo pipefail

REPO="${NARCOSCOPE_REPO:-/opt/narcoscope}"
DEPLOY_KEY="${NARCOSCOPE_DEPLOY_KEY:-/root/.ssh/narcoscope_deploy}"
BRANCH="${NARCOSCOPE_BRANCH:-main}"
RUN_ROOT="${NARCOSCOPE_RUN_ROOT:-/var/tmp}"
printf -v GIT_SSH_COMMAND 'ssh -i %q -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new' "$DEPLOY_KEY"
export GIT_SSH_COMMAND
GENERATED_PATHS=(
  "src/data"
  "public/data/narcoscope-palimpsest-v1.json"
  "public/news"
)

log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }

RUN_BASE=""
RUN_DIR=""
WORKTREE_ADDED=0

cleanup() {
  local result=$?
  trap - EXIT
  if [[ "$WORKTREE_ADDED" -eq 1 ]]; then
    if ! git -C "$REPO" worktree remove --force "$RUN_DIR"; then
      log "WARN: could not remove disposable worktree $RUN_DIR"
      [[ "$result" -ne 0 ]] || result=1
    fi
  fi
  if [[ -n "$RUN_BASE" && -d "$RUN_BASE" ]]; then
    if ! rmdir -- "$RUN_BASE" 2>/dev/null; then
      log "WARN: incomplete disposable directory remains at $RUN_BASE"
      [[ "$result" -ne 0 ]] || result=1
    fi
  fi
  exit "$result"
}

trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

[[ -d "$REPO" ]] || { log "FAIL: repository directory does not exist: $REPO"; exit 1; }
[[ -d "$RUN_ROOT" && -w "$RUN_ROOT" ]] || { log "FAIL: run root is not a writable directory: $RUN_ROOT"; exit 1; }
git check-ref-format "refs/heads/${BRANCH}" >/dev/null 2>&1 || { log "FAIL: invalid branch name"; exit 1; }

log "collector start (repo=$REPO branch=$BRANCH)"

# Build from the fetched remote ref in a detached worktree. The service checkout
# is only the Git object store and script source; its working tree is never reset
# or cleaned, including after a failed upstream refresh.
git -C "$REPO" fetch --quiet origin "$BRANCH"
RUN_BASE="$(mktemp -d "${RUN_ROOT%/}/narcoscope-collector.XXXXXX")"
RUN_DIR="$RUN_BASE/worktree"
git -C "$REPO" worktree add --quiet --detach "$RUN_DIR" "origin/${BRANCH}"
WORKTREE_ADDED=1
cd "$RUN_DIR"
log "isolated run directory ready: $RUN_DIR"

# Dependencies (fast no-op when the lockfile is unchanged).
npm ci --no-audit --no-fund --silent

# Fetch + transform + validate. Non-zero here aborts before any push.
if ! npm run data:refresh; then
  log "FAIL: data:refresh did not pass validation; nothing pushed"
  exit 1
fi

# Push only generated data and derived public artifacts, only if any changed.
# `git status` also sees newly generated, previously untracked files.
if [[ -z "$(git status --porcelain -- "${GENERATED_PATHS[@]}")" ]]; then
  log "no data changes"
  exit 0
fi

git add -- "${GENERATED_PATHS[@]}"
git -c user.name="narcoscope-collector" \
    -c user.email="collector@narcoscope.local" \
    commit --quiet -m "data: automated refresh $(date -u +%Y-%m-%dT%H:%MZ)

Regenerated by the Hetzner collector; passed tsc + the full test suite before push."
git push --quiet origin "HEAD:${BRANCH}"
log "pushed refreshed data; Vercel will redeploy"
