#!/usr/bin/env bash
# =============================================================================
# NarcoScope 24/7 data collector
# =============================================================================
# Runs the open-data pipeline (fetch → transform → VALIDATE), and pushes the
# refreshed datasets only if they changed AND passed the test gate. Designed to
# run on the Hetzner box under a systemd timer.
#
# Safety: `npm run data:refresh` runs tsc + the full vitest suite (including the
# dataset-integrity tests) as a hard gate. If validation fails, the script exits
# non-zero and pushes NOTHING — bad data never reaches the live site.
# =============================================================================
set -euo pipefail

REPO="${NARCOSCOPE_REPO:-/opt/narcoscope}"
DEPLOY_KEY="${NARCOSCOPE_DEPLOY_KEY:-/root/.ssh/narcoscope_deploy}"
BRANCH="${NARCOSCOPE_BRANCH:-main}"
export GIT_SSH_COMMAND="ssh -i ${DEPLOY_KEY} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new"
GENERATED_PATHS=(
  "src/data"
  "public/data/narcoscope-palimpsest-v1.json"
  "public/news"
)

log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }

cd "$REPO"
log "collector start (repo=$REPO branch=$BRANCH)"

# Always start from a clean, current main so a local wobble can't accumulate.
git fetch --quiet origin "$BRANCH"
git reset --quiet --hard "origin/${BRANCH}"
git clean -qfd -- "${GENERATED_PATHS[@]}" data-raw 2>/dev/null || true

# Dependencies (fast no-op when the lockfile is unchanged).
npm ci --no-audit --no-fund --silent

# Fetch + transform + validate. Non-zero here aborts before any push.
if ! npm run data:refresh; then
  log "FAIL: data:refresh did not pass validation — nothing pushed"
  exit 1
fi

# Push only generated data and derived public artifacts, only if any changed.
# `git status` also sees newly generated, previously untracked files.
if [[ -z "$(git status --porcelain -- "${GENERATED_PATHS[@]}")" ]]; then
  log "no data changes"
  exit 0
fi

git add -- "${GENERATED_PATHS[@]}"
git -c user.name="narcoscope-collector" \
    -c user.email="collector@narcoscope.local" \
    commit --quiet -m "data: automated refresh $(date -u +%Y-%m-%dT%H:%MZ)

Regenerated by the Hetzner collector; passed tsc + the full test suite before push."
git push --quiet origin "HEAD:${BRANCH}"
log "pushed refreshed data — Vercel will redeploy"
