// GENERATED by scripts/convert/gen-us-states.mjs — do not edit by hand.
// Joins CDC overdose jurisdictions (by abbr) to the us-atlas choropleth (by
// FIPS), and carries 2023 Census population for per-100k rates.
export interface UsState { abbr: string; fips: string; name: string; population: number }

export const US_STATES: UsState[] = [
  {
    "abbr": "AL",
    "fips": "01",
    "name": "Alabama",
    "population": 5108468
  },
  {
    "abbr": "AK",
    "fips": "02",
    "name": "Alaska",
    "population": 733406
  },
  {
    "abbr": "AZ",
    "fips": "04",
    "name": "Arizona",
    "population": 7431344
  },
  {
    "abbr": "AR",
    "fips": "05",
    "name": "Arkansas",
    "population": 3067732
  },
  {
    "abbr": "CA",
    "fips": "06",
    "name": "California",
    "population": 38965193
  },
  {
    "abbr": "CO",
    "fips": "08",
    "name": "Colorado",
    "population": 5877610
  },
  {
    "abbr": "CT",
    "fips": "09",
    "name": "Connecticut",
    "population": 3617176
  },
  {
    "abbr": "DE",
    "fips": "10",
    "name": "Delaware",
    "population": 1031890
  },
  {
    "abbr": "DC",
    "fips": "11",
    "name": "District of Columbia",
    "population": 678972
  },
  {
    "abbr": "FL",
    "fips": "12",
    "name": "Florida",
    "population": 22610726
  },
  {
    "abbr": "GA",
    "fips": "13",
    "name": "Georgia",
    "population": 11029227
  },
  {
    "abbr": "HI",
    "fips": "15",
    "name": "Hawaii",
    "population": 1435138
  },
  {
    "abbr": "ID",
    "fips": "16",
    "name": "Idaho",
    "population": 1964726
  },
  {
    "abbr": "IL",
    "fips": "17",
    "name": "Illinois",
    "population": 12549689
  },
  {
    "abbr": "IN",
    "fips": "18",
    "name": "Indiana",
    "population": 6862199
  },
  {
    "abbr": "IA",
    "fips": "19",
    "name": "Iowa",
    "population": 3207004
  },
  {
    "abbr": "KS",
    "fips": "20",
    "name": "Kansas",
    "population": 2940546
  },
  {
    "abbr": "KY",
    "fips": "21",
    "name": "Kentucky",
    "population": 4526154
  },
  {
    "abbr": "LA",
    "fips": "22",
    "name": "Louisiana",
    "population": 4573749
  },
  {
    "abbr": "ME",
    "fips": "23",
    "name": "Maine",
    "population": 1395722
  },
  {
    "abbr": "MD",
    "fips": "24",
    "name": "Maryland",
    "population": 6180253
  },
  {
    "abbr": "MA",
    "fips": "25",
    "name": "Massachusetts",
    "population": 7001399
  },
  {
    "abbr": "MI",
    "fips": "26",
    "name": "Michigan",
    "population": 10037261
  },
  {
    "abbr": "MN",
    "fips": "27",
    "name": "Minnesota",
    "population": 5737915
  },
  {
    "abbr": "MS",
    "fips": "28",
    "name": "Mississippi",
    "population": 2939690
  },
  {
    "abbr": "MO",
    "fips": "29",
    "name": "Missouri",
    "population": 6196156
  },
  {
    "abbr": "MT",
    "fips": "30",
    "name": "Montana",
    "population": 1132812
  },
  {
    "abbr": "NE",
    "fips": "31",
    "name": "Nebraska",
    "population": 1978379
  },
  {
    "abbr": "NV",
    "fips": "32",
    "name": "Nevada",
    "population": 3194176
  },
  {
    "abbr": "NH",
    "fips": "33",
    "name": "New Hampshire",
    "population": 1402054
  },
  {
    "abbr": "NJ",
    "fips": "34",
    "name": "New Jersey",
    "population": 9290841
  },
  {
    "abbr": "NM",
    "fips": "35",
    "name": "New Mexico",
    "population": 2114371
  },
  {
    "abbr": "NY",
    "fips": "36",
    "name": "New York",
    "population": 19571216
  },
  {
    "abbr": "NC",
    "fips": "37",
    "name": "North Carolina",
    "population": 10835491
  },
  {
    "abbr": "ND",
    "fips": "38",
    "name": "North Dakota",
    "population": 783926
  },
  {
    "abbr": "OH",
    "fips": "39",
    "name": "Ohio",
    "population": 11785935
  },
  {
    "abbr": "OK",
    "fips": "40",
    "name": "Oklahoma",
    "population": 4053824
  },
  {
    "abbr": "OR",
    "fips": "41",
    "name": "Oregon",
    "population": 4233358
  },
  {
    "abbr": "PA",
    "fips": "42",
    "name": "Pennsylvania",
    "population": 12961683
  },
  {
    "abbr": "RI",
    "fips": "44",
    "name": "Rhode Island",
    "population": 1095962
  },
  {
    "abbr": "SC",
    "fips": "45",
    "name": "South Carolina",
    "population": 5373555
  },
  {
    "abbr": "SD",
    "fips": "46",
    "name": "South Dakota",
    "population": 919318
  },
  {
    "abbr": "TN",
    "fips": "47",
    "name": "Tennessee",
    "population": 7126489
  },
  {
    "abbr": "TX",
    "fips": "48",
    "name": "Texas",
    "population": 30503301
  },
  {
    "abbr": "UT",
    "fips": "49",
    "name": "Utah",
    "population": 3417734
  },
  {
    "abbr": "VT",
    "fips": "50",
    "name": "Vermont",
    "population": 647464
  },
  {
    "abbr": "VA",
    "fips": "51",
    "name": "Virginia",
    "population": 8715698
  },
  {
    "abbr": "WA",
    "fips": "53",
    "name": "Washington",
    "population": 7812880
  },
  {
    "abbr": "WV",
    "fips": "54",
    "name": "West Virginia",
    "population": 1770071
  },
  {
    "abbr": "WI",
    "fips": "55",
    "name": "Wisconsin",
    "population": 5910955
  },
  {
    "abbr": "WY",
    "fips": "56",
    "name": "Wyoming",
    "population": 584057
  }
]

/** NYC ('YC') is a CDC jurisdiction with no separate map shape; rates only. */
export const US_JURISDICTION_POP: Record<string, number> = {
  "YC": 8258035,
  "US": 334914895
}

export const FIPS_TO_ABBR: Record<string, string> =
  Object.fromEntries(US_STATES.map((s) => [s.fips, s.abbr]))
